// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeSb_6aMwHM8pqo0MqKKyHgCMPdAW3taE',
    appId: '1:527243139289:web:085699fb2eea4e9ddcc6c8',
    messagingSenderId: '527243139289',
    projectId: 'chatflut-4ec1e',
    authDomain: 'chatflut-4ec1e.firebaseapp.com',
    storageBucket: 'chatflut-4ec1e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7BP_vdO5PpfLQ9BNJVTGmgyDsHEFb8pM',
    appId: '1:527243139289:android:924fbd5bc827f3c9dcc6c8',
    messagingSenderId: '527243139289',
    projectId: 'chatflut-4ec1e',
    storageBucket: 'chatflut-4ec1e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC196zAyF42-qb-7xqd044DeQWNQIkQldk',
    appId: '1:527243139289:ios:b0092ae87333f1c9dcc6c8',
    messagingSenderId: '527243139289',
    projectId: 'chatflut-4ec1e',
    storageBucket: 'chatflut-4ec1e.appspot.com',
    iosBundleId: 'com.example.chatflut',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC196zAyF42-qb-7xqd044DeQWNQIkQldk',
    appId: '1:527243139289:ios:88b52cda05db05e1dcc6c8',
    messagingSenderId: '527243139289',
    projectId: 'chatflut-4ec1e',
    storageBucket: 'chatflut-4ec1e.appspot.com',
    iosBundleId: 'com.example.chatflut.RunnerTests',
  );
}
